### ISSUE TITLE
Cuda out of Memory 

### ISSUE THREAD

**Issue by hcagri** [dvl-tum/SUSHI#20]
>  /truba/home/hbilgi/miniconda3/envs/py_cuda/lib/python3.8/site-packages/torch_geometric/deprecation.py:22: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
Experiment ID: /truba/home/hbilgi/dev/SUSHI/outputs/experiments/example_mot17_training_fastreid_msmt_BOT_R50_ibn_09-05_14:24:29.837579
Experiment Mode: train
----- CONFIG -----
experiment_mode : train
run_id : example_mot17_training_fastreid_msmt_BOT_R50_ibn
connectivity : chunk
data_path : /truba/home/hbilgi/dev/thesis/mot_data
output_path : /truba/home/hbilgi/dev/SUSHI/outputs
seed : 0
cuda : True
num_workers : 4
train_splits : ['mot17-train-all']
val_splits : ['mot17-train-all']
test_splits : [None]
cval_seqs : mot17-train-all
det_file : det
save_cp : True
feature_embedding_model_path : 
hicl_model_path : 
load_train_ckpt : False
share_weights : all_but_first
node_level_embed : False
edge_level_embed : True
reid_arch : fastreid_msmt_BOT_R50_ibn
reid_sim_fn : l2
edge_sim_fn : l2
node_dim : 2048
l2_norm_reid : False
reid_embeddings_dir : reid_fastreid_msmt_BOT_R50_ibn
node_embeddings_dir : node_fastreid_msmt_BOT_R50_ibn
num_epoch : 250
num_batch : 8
lr : 0.0003
gamma : 1
weight_decay : 0.0001
augmentation : False
train_dataset_frame_overlap : 20
start_eval : 100
no_fp_loss : False
min_track_len : 2
rounding_method : exact
no_interpolate : False
top_k_nns : 10
frames_per_graph : 512
frames_per_level : [2, 4, 8, 16, 32, 64, 128, 256, 512]
pruning_method : ['geometry', 'motion_005', 'motion_005', 'motion_005', 'motion_005', 'motion_005', 'motion_005', 'motion_005', 'motion_005']
hicl_depth : 9
node_id_min_ratio : 0.5
depth_pretrain_iteration : 500
motion_max_length : [2, 4, 8, 16, 32, 64, 128, 256]
motion_pred_length : [2, 4, 8, 16, 32, 64, 128, 256]
interpolate_motion : True
linear_center_only : True
do_hicl_feats : False
hicl_feats_args : {}
reid_img_h : 256
reid_img_w : 128
zero_nodes : True
mpn_use_motion : [False, True, True, True, True, True, True, True, True]
mpn_use_reid_edge : [True, True, True, True, True, True, True, True, True]
mpn_use_pos_edge : [True, True, True, True, True, True, True, True, True]
old_experiments : [None]
mot_sub_folder : mot_files
gt_training_min_vis : 0.0
gt_assign_min_iou : 0.5
min_iou_bb_wiggling : 0.85
min_ids_to_drop_perc : 0
max_ids_to_drop_perc : 0.1
min_detects_to_drop_perc : 0
max_detects_to_drop_perc : 0.2
evaluation_graph_overlap_ratio : 0.5
solver_backend : pulp
symmetric_edges : True
verbose_iteration : 10
device : cuda:0
experiment_path : /truba/home/hbilgi/dev/SUSHI/outputs/experiments/example_mot17_training_fastreid_msmt_BOT_R50_ibn_09-05_14:24:29.837579
VIDEO_COLUMNS : ['frame_path', 'frame', 'ped_id', 'bb_left', 'bb_top', 'bb_width', 'bb_height', 'bb_right', 'bb_bot']
TRACKING_OUT_COLS : ['frame', 'ped_id', 'bb_left', 'bb_top', 'bb_width', 'bb_height', 'conf', 'x', 'y', 'z']
do_motion : True
------------------
> Loading processed dets for sequence MOT17-02-SDP from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-02-SDP/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-02-FRCNN from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-02-FRCNN/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-02-DPM from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-02-DPM/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-04-SDP from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-04-SDP/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-04-FRCNN from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-04-FRCNN/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-04-DPM from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-04-DPM/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-05-SDP from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-05-SDP/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-05-FRCNN from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-05-FRCNN/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-05-DPM from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-05-DPM/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-09-SDP from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-09-SDP/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-09-FRCNN from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-09-FRCNN/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-09-DPM from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-09-DPM/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-10-SDP from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-10-SDP/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-10-FRCNN from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-10-FRCNN/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-10-DPM from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-10-DPM/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-11-SDP from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-11-SDP/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-11-FRCNN from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-11-FRCNN/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-11-DPM from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-11-DPM/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-13-SDP from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-13-SDP/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-13-FRCNN from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-13-FRCNN/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-13-DPM from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-13-DPM/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-02-SDP from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-02-SDP/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-02-FRCNN from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-02-FRCNN/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-02-DPM from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-02-DPM/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-04-SDP from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-04-SDP/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-04-FRCNN from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-04-FRCNN/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-04-DPM from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-04-DPM/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-05-SDP from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-05-SDP/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-05-FRCNN from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-05-FRCNN/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-05-DPM from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-05-DPM/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-09-SDP from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-09-SDP/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-09-FRCNN from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-09-FRCNN/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-09-DPM from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-09-DPM/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-10-SDP from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-10-SDP/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-10-FRCNN from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-10-FRCNN/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-10-DPM from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-10-DPM/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-11-SDP from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-11-SDP/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-11-FRCNN from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-11-FRCNN/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-11-DPM from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-11-DPM/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-13-SDP from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-13-SDP/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-13-FRCNN from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-13-FRCNN/processed_data/det/det.pkl
Loading processed dets for sequence MOT17-13-DPM from /truba/home/hbilgi/dev/thesis/mot_data/MOT17/train/MOT17-13-DPM/processed_data/det/det.pkl
Tracking MOT17-02-SDP
Tracking MOT17-02-FRCNN
Tracking MOT17-02-DPM
Tracking MOT17-04-SDP
Tracking MOT17-04-FRCNN
Tracking MOT17-04-DPM
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    hicl_tracker.train()
  File "/truba/home/hbilgi/dev/SUSHI/src/tracker/hicl_tracker.py", line 456, in train
    _, _ = self.track(self.val_dataset, output_path=osp.join(self.config.experiment_path, 'oracle'), mode='val', oracle=True)
  File "/truba/home/hbilgi/dev/SUSHI/src/tracker/hicl_tracker.py", line 548, in track
    hicl_graphs, _, logs_all = self.hicl_forward(hicl_graphs = hicl_graphs, 
  File "/truba/home/hbilgi/dev/SUSHI/src/tracker/hicl_tracker.py", line 333, in hicl_forward
    curr_batch, _ = self._hicl_to_curr(hicl_graphs=hicl_graphs)  # Create curr_graphs from hierarachical graphs            
  File "/truba/home/hbilgi/dev/SUSHI/src/tracker/hicl_tracker.py", line 185, in _hicl_to_curr
    batch.pruning_score = compute_giou_fwrd_bwrd_motion_sim(batch, motion_pred)
  File "/truba/home/hbilgi/dev/SUSHI/src/utils/motion_utils.py", line 90, in compute_giou_fwrd_bwrd_motion_sim
    fwrd_start_box = fwrd_pred[row].gather(1, t_diff_fwrd[:,None, None].expand(-1, -1, 4))[:, 0]
RuntimeError: CUDA out of memory. Tried to allocate 121.04 GiB (GPU 0; 79.35 GiB total capacity; 2.57 GiB already allocated; 74.24 GiB free; 4.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Hi, I tried to run the code with default configurations and started training MOT17 public detections. However, I get the error above. Is there a problem with my system or does this method require more than 120 GB of GPU memory. 

Thanks.

**Comment by ocetintas** [comment]
No the method does not require 120 GB of GPU memory and you should be able to run the code with your current hardware (80 GB GPU).

**Comment by hcagri** [comment]
I am closing the issue since it is a duplicate of [#11 ](https://github.com/dvl-tum/SUSHI/issues/11). When I change the number of frames from 512 to 128 as suggested in that issue, the problem is resolved. But I still could not find a solution why it is not working with 512 frames. Thanks
